[versions]
kotlin = "2.0.0"
gradle-ktlint = "12.1.1"
antlr = "4.13.1"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
antlr = { group = "org.antlr", name = "antlr4-runtime", version.ref = "antlr" }

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
gradleKtlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "gradle-ktlint" }
